#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_getprofile 142 2022-11-24 17:38:35Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}
. ${0%/*}/.irmc_env

PMSBASE="Systems/0/Oem/ts_fujitsu/ProfileManagement"
PMSACTION="${PMSBASE}/Actions/FTSProfileManagement."
SUBTREE=Server/SystemConfig/${1:-IrmcConfig/System}
STORENAME=${SUBTREE##*/}
JSON=${2:-$JSONFILE}

msg "Talking with iRMC $iRMC as user \"$USER\" ..."
msg "Removing existing profile \"$STORENAME\" if necessary ..."
[ "$(irmc_cmd get $PMSBASE|jq -r '.Profiles[]|select(.Name == '\"$STORENAME\"')|.Name')" = $STORENAME ] && \
	irmc_cmd post ${PMSACTION}RemoveProfile -d '{"ProfileName":'\"$STORENAME\"'}'  >/dev/null

msg -n "Obtaining profile ${SUBTREE#Server/SystemConfig/} ..."
irmc_cmd post ${PMSACTION}ObtainProfile -d '{"Path":'\"${SUBTREE}\"',"Format":"JSON"}' || exit 2 

TASK=$(tr -d "\r" <$HEADERFILE | awk -F: '/^Location/ {print $2}')
msg -n "Waiting for completion of task ${TASK##*/} ..."
while [ "$(irmc_cmd get $TASK | jq -r .TaskState)" != "Completed" ]
do
	echo -n "."
	sleep 5
done
irmc_cmd get $TASK | jq -rj '"Status=",.TaskStatus,"\n"'

msg -n "Downloading profile to file \"$JSON\" ..."
irmc_cmd post ${PMSACTION}DownloadProfile -d '{"ProfileName":'\"$STORENAME\"'}' -o $JSON 

msg "Cleaning up ..."
irmc_cmd delete $TASK
