#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_reset 142 2022-11-24 17:38:35Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}

irmc_cmd post Managers/iRMC/Actions/Manager.Reset -i | head -1
