#!/bin/bash
# $Id: irmc_showenv 135 2022-11-19 10:07:24Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}
#
# Show effective vars for iRMCtools

export PATH=$PATH:${0%/*}
#
. ${0%/*}/.irmc_env
for VAR in iRMC iRMC_FQDN iRMC_IP USER PASSWD session_id session_token
do
	printf "%-16s %s\n" "${VAR}:" "$(eval echo \$$VAR)"
done
