#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_showstatus 142 2022-11-24 17:38:35Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}

irmc_cmd get Chassis/0/Oem/ts_fujitsu/ComponentStatusOverview | tr -d '",' | awk -F: '
	/SumStatus:/ { print $1 }' | while read component
	do
		irmc_cmd get Chassis/0/Oem/ts_fujitsu/ComponentStatus/${component/SumStatus/}s |\
			jq -r '.Members[]."@odata.id"' | while read subcomponent
				do
					irmc_cmd get $subcomponent | jq -rj '.Designation," ",.SignalStatus,"\n"'
				done
	done
