#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_setprofile 142 2022-11-24 17:38:35Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}
. ${0%/*}/.irmc_env

PMSBASE="Systems/0/Oem/ts_fujitsu/ProfileManagement"
PMSACTION="${PMSBASE}/Actions/FTSProfileManagement."
JSON=${1:-$JSONFILE}

msg "Talking with iRMC $iRMC as user \"$USER\" ..."
msg -n "Applying profile \"$JSON\" - please wait ..."

sed -E '/\"IrmcConfig|\"BiosConfig/ a \\t"@Processing":"execute",' <$JSON >$JSON.$$
ContentType="multipart/form-data" irmc_cmd post ${PMSACTION}ApplyProfile -F "data=@${1:-$JSON.$$}" || exit 2
rm $JSON.$$

TASK=$(tr -d "\r" <$HEADERFILE | awk -F: '/^Location/ {print $2}')
msg -n "Waiting for completion of task ${TASK##*/} ..."
while [ "$(irmc_cmd get $TASK | jq -r .TaskState)" != "Completed" ]
do
        echo -n "."
        sleep 5
done
irmc_cmd get $TASK | jq -rj '"Status=",.TaskStatus,"\n"'

msg "Cleaning up ..."
irmc_cmd delete $TASK

