#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_shownic 135 2022-11-19 10:07:24Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}

echo "#########################################################"
echo "$(irmc_cmd get Systems/0 | jq -rj '.Model," ",.Name,"\n"') $iRMC"
echo "#########################################################"
echo

MACCOMMAND=Systems/0/EthernetInterfaces
SLOTCOMMAND=Chassis/0/NetworkAdapters

echo -e "LAN MAC addresses:\n"

echo "MAC               Ctrl Port Link     Name"
echo "================= ==== ==== ======== ========================================="
irmc_cmd get ${MACCOMMAND} |\
       	jq -r '.Members[]."@odata.id"' |\
	while read EP
	do
		irmc_cmd get ${EP#*v1/} |\
		       	jq -r '.PermanentMACAddress,.Oem.ts_fujitsu.ControllerNumber,.Oem.ts_fujitsu.PortNumber,.LinkStatus,.Name' | xargs |\
			while read MAC CTRL PORT LINK NAME
			do
		       		printf "%s %4d %4d %-8s %s\n" $MAC $CTRL $PORT $LINK "$NAME"
			done
	done
echo -e "\n\nPCI-Cards slot mapping ..."
echo -e "\nSlots:\n======"
irmc_cmd get ${SLOTCOMMAND}  |\
       	jq -r '.Members[]."@odata.id"' |\
	while read EP
	do
		irmc_cmd get ${EP#*v1/} |\
			jq -rj '.Model,"; ",.Controllers[0].Location.Info' |\
			sed 's/\[ 0 : // 
			     s/\]$//' |\
			awk -F\; '{printf("%-40s %s",$1,$2);}'
		echo
	done
