#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_chbios 146 2022-11-25 08:43:37Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}
. ${0%/*}/.irmc_env

[ "$1" ] || error 1 "Usage: ${0##*/} true|false"

OLD=/tmp/biosold.json
NEW=/tmp/biosnew.json

irmc_getprofile IrmcConfig/ServerManagement $OLD
msg "Setting BIOS update to $1"
jq ".Server.SystemConfig.IrmcConfig.ServerManagement.PermanentBiosConfigStorageEnabled=$1" <$OLD >$NEW
irmc_setprofile $NEW
msg "Important: Changes will only be effective after server reboot"
