#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_cmd 179 2023-03-29 12:41:05Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}

[ "$DEBUG" ] && set -x

# get common settings like ip address and user credentials (iRMC, iRMC_FQDN, USER, PASSWD, CACERT)
DIR=${0%/*}
PROG=${0##*/}
. ${DIR}/.irmc_env

# just a default cmd ==> w/o params get SessionService
METHOD=${1:-GET}
CMD=${2:-'SessionService'}; shift 2
CMD=${CMD#*redfish/v1/} 		# make it more robust 
CMD=$(echo $CMD | sed 's;^/;;')		# make it more robust

[ "$DEBUG" ] && echo "$METHOD $CMD $*" >>$REDFISHFILE
[ "$DEBUG" ] && CAT="tee -a $OUTPUTFILE" || CAT="cat"
[ -r "$CACERT" ] && CERTOPT="--cacert $CACERT" || { CERTOPT="-k"; [ "$WARNING" ] && echo "unsecure mode!" >&2; }
 
if [ "$session_token" ]
then
	# With Session ID (you have to run 'eval $(irmc_login)' before running this script and afterwards "eval $(irmc_logout)")
	AUTH="-H X-Auth-Token:$session_token"
else
	# w/o Session ID = One Time Authorization
	AUTH="-K -"
fi
echo 'user = "'$USER:$PASSWD'"' | curl "https://$iRMC/redfish/v1/$CMD" -X ${METHOD^^} $AUTH -H "Content-Type: $ContentType" $CERTOPT $DEFAULTOPTIONS "$@" | $CAT
echo
result=$(head -1 $HEADERFILE)
[[ "$result" =~ 2[0-9][0-9] ]] || { echo $result >&2; exit 1; }
