#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: irmc_sso 144 2022-11-24 18:22:59Z HMBJOrth $
# for documentation see https://github.com/fujitsu/iRMCtools

export PATH=$PATH:${0%/*}
. ${0%/*}/.irmc_env

SESSION=$(irmc_cmd post SessionService/Actions/Oem/FTSSessionService.CreateSSOSession \
	-d '{"RoleId": "Operator", "UseVideoRedirection": true, "UseRemoteStorage": false}' | \
		jq -rj '"RfSessToken=",."X-Auth-Token","&SessId=",.Id')

for cmd in login report.xml viewer.html
do
	$BROWSER "$iRMC/$cmd?$SESSION"
done
